fix: GitHub ActionsでGoogleService-Info.plistを生成するように修正

diff --git a/.github/workflows/deliver.yml b/.github/workflows/deliver.yml
--- a/.github/workflows/deliver.yml
+++ b/.github/workflows/deliver.yml
@@ -81,6 +81,17 @@ jobs:
             exit 1
           fi
 
+      - name: Create GoogleService-Info.plist for iOS
+        env:
+          GOOGLE_SERVICE_INFO_PLIST_BASE64: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST_BASE64 }}
+        run: |
+          if [ -n "$GOOGLE_SERVICE_INFO_PLIST_BASE64" ]; then
+            echo -n "$GOOGLE_SERVICE_INFO_PLIST_BASE64" | base64 --decode > flutter/ios/Runner/GoogleService-Info.plist
+          else
+            echo "Error: GOOGLE_SERVICE_INFO_PLIST_BASE64 secret not set"
+            exit 1
+          fi
+
       - name: Run flutter pub get
         run: flutter pub get
         working-directory: flutter
