feat: firebase optionsをsecretsから生成

diff --git a/.github/workflows/deliver.yml b/.github/workflows/deliver.yml
--- a/.github/workflows/deliver.yml
+++ b/.github/workflows/deliver.yml
@@ -70,6 +70,17 @@ jobs:
         run: flutter --version
         working-directory: flutter
 
+      - name: Create firebase_options_prod.dart
+        env:
+          FIREBASE_OPTIONS_PROD_BASE64: ${{ secrets.FIREBASE_OPTIONS_PROD_BASE64 }}
+        run: |
+          if [ -n "$FIREBASE_OPTIONS_PROD_BASE64" ]; then
+            echo -n "$FIREBASE_OPTIONS_PROD_BASE64" | base64 --decode > flutter/lib/firebase_options_prod.dart
+          else
+            echo "Error: FIREBASE_OPTIONS_PROD_BASE64 secret not set"
+            exit 1
+          fi
+
       - name: Run flutter pub get
         run: flutter pub get
         working-directory: flutter
